### ISSUE TITLE
How to get first snapshot to work

### ISSUE THREAD

**Issue by burggraf** [maxpert/marmot#32] opened 2022-11-01 17:17 UTC
As a test, I have two machines with public IPs on the internet, both running `pocketbase`, `nats-server`, and `marmot`.  If I create my admin user and collections on the first machine, how can I get the second machine to migrate over that initial set of data and then start replicating things in both directions after the initial snapshot migration?

**Comment by maxpert** [comment] 2022-11-01 20:09
Marmot let's you just take a snapshot and quit itself, you can do something like this:

```
marmot -c ./config.toml -save-snapshot
```

This will bring up marmot, take and upload snapshot then quit. Now on the peer machine do if you make sure [there is no `seq_map_path` file](https://github.com/maxpert/marmot/blob/master/config.toml#L11) the booting Marmot will try to restore snapshot from NATS before starting replication.

**Comment by burggraf** [comment] 2022-11-01 20:22
I think I tried that but will try it again.  BTW, `-c` no longer works in the version 0.6.0 that I downloaded from the releases page so I have to use all command-line parameters.

**Comment by burggraf** [comment] 2022-11-01 20:28
When I try `-save-snapshot` I get:

```
marmot \
>     -db-path /pb_data/data.db \
>     -node-id 1 \
>     -seq-map-path "/tmp/seq-map-1" \
>     -log-replicas 1 \
>     -shards 8 \
>     -max-log-entries 1024 \
>     -compress true \
>     -enable-snapshot true \
>     -nats-url "nats://my.first.server:4222, nats://my.second.server:4222" \
>     -subject-prefix "marmot-change-log" \
>     -stream-prefix "marmot-changes" \
>     -verbose -save-snapshot
8:26PM PNC Unable to initialize replicators error="nats: JetStream system temporarily unavailable"
panic: Unable to initialize replicators
```

**Comment by maxpert** [comment] 2022-11-01 21:30
> 8:26PM PNC Unable to initialize replicators error="nats: JetStream system temporarily unavailable"
> panic: Unable to initialize replicators

This sounds like some sort of [NATS problem](https://github.com/nats-io/nats-server/issues/2922). What version of NATS are you using, and have you configured NATS server with JetStream?

**Comment by maxpert** [comment] 2022-11-01 21:30
> I think I tried that but will try it again. BTW, `-c` no longer works in the version 0.6.0 that I downloaded from the releases page so I have to use all command-line parameters.

Sorry not `-c` I meant to say `-config`

**Comment by burggraf** [comment] 2022-11-01 21:32
```
nats-server --version
nats-server: v2.9.4
```
config:

```
listen: 0.0.0.0:4222
server_name: natt2

accounts: {
  $SYS: {
    users: [
      {user: admin, password: changeit}
    ]
  },
}

cluster {
  name: rack
  listen: 0.0.0.0:4248
  routes = [
    nats-route://my.first.server:4248
    nats-route://my.second.server:4248
  ]
}

jetstream: enabled
jetstream {
  store_dir: /tmp/nats2
  max_mem: 256M
  max_file: 1G
}
```

**Comment by burggraf** [comment] 2022-11-01 21:33
Note: this configuration works for me once I manually get things started, so `nats-server` is working (it's replicating data, etc.)  I just can't get it to properly bootstrap a new node.

**Comment by burggraf** [comment] 2022-11-01 21:42
> > I think I tried that but will try it again. BTW, `-c` no longer works in the version 0.6.0 that I downloaded from the releases page so I have to use all command-line parameters.
> 
> Sorry not `-c` I meant to say `-config`

There is no `-config` option either:

```
marmot --help
Usage of marmot:
  -cleanup
    	Only cleanup marmot triggers and changelogs
  -compress
    	Enable message compression
  -db-path string
    	Path to SQLite database (default "/tmp/marmot.db")
  -enable-snapshot
    	Restore snapshot at boot (default true)
  -log-replicas int
    	Number of copies to be committed for single change log (default 1)
  -max-log-entries int
    	Maximum number of change log entries to persist (default 1024)
  -nats-url string
    	NATS server URL (default "nats://127.0.0.1:4222")
  -node-id uint
    	Node ID (default 13153039197179287978)
  -save-snapshot
    	Only take snapshot and upload
  -seq-map-path string
    	Path to stream sequence map (default "/tmp/seq-map.cbor")
  -shards uint
    	Number of stream shards to distribute change log on (default 8)
  -stream-prefix string
    	Prefix for publish subjects (default "marmot-changes")
  -subject-prefix string
    	Prefix for publish subjects (default "marmot-change-log")
  -verbose
    	Log debug level
```

**Comment by maxpert** [comment] 2022-11-01 21:47
I am sorry I've not cut the release from master so far, and I just realized that change has been sitting there. I will get the [0.7.0-RC.1](https://github.com/maxpert/marmot/releases/tag/v0.7.0-RC.1) to 0.7.0 pretty soon. That moves configurations to files, and makes it lot more easy. Let me try the cold boot on my side (because I've been doing it on my side for a while now), follow up here.

**Comment by burggraf** [comment] 2022-11-01 22:21
I noticed you CAN use a config file if you call it `marmot.toml` and don't use any command-line parameter (at least I **think** it's using this config file) but obviously using a `-config` clp would be much more convenient.

**Comment by maxpert** [comment] 2022-11-01 22:34
The RC version that I posted moves to `-config` instead of CLI parameters. CLI params were getting just too crowded, so I moved it to config file. I just tried saving snapshot, and then just spinning up a node without any DB there to force it restore the restore. It worked flawlessly. I am trying to reproduce your NATS error since I believe it has something to do with error on NATS, rather than Marmot.

**Comment by maxpert** [comment] 2022-11-01 22:36
Sounds like the NATS server storage directory is having some problem in your case. Can you check your NATS server storage directory and maybe clean it up for fresh boot?

**Comment by burggraf** [comment] 2022-11-01 22:36
Can you document the flow here? i.e.:
- node 1: start pocketbase
- node 1: start nats-server
- wait 10 seconds
- node 1: start marmot
- later....
- node 2: start pocketbase
- node 2: start nats-server
- wait 10 seconds
- node 2: start marmot

**Comment by burggraf** [comment] 2022-11-01 22:37
> Sounds like the NATS server storage directory is having some problem in your case. Can you check your NATS server storage directory and maybe clean it up for fresh boot?

How should I do that?  I'm running in docker containers on each machine, so the `/tmp` folder should be empty each time I start it up.

**Comment by burggraf** [comment] 2022-11-01 22:43
I can get it to work but the timing and order of things is super finicky.  I have to shutdown pocketbase on node 2, then run a snapshot on node 1, then run marmot on node 2 then start up pocketbase on node 2 again.

I think there should be a switch or something to initialize a secondary (or tertiary) node.

**Comment by burggraf** [comment] 2022-11-01 22:49
I guess the main issue I'm having is this:  marmot crashes if only the current node is running.  So I can't easily bootstrap things.  I want to start up pocketbase, create an admin, create a collection, then create a snapshot, then start up the 2nd node so they're in sync.

If I start up both nodes, then pocketbase is already running on the second node and it creates the database, and it doesn't sync.  What's the best way to do this programmatically, so I can start with one node, seed it with data, then start up additional nodes?

**Comment by maxpert** [comment] 2022-11-01 22:55
> Can you document the flow here? i.e.:
> 
> * node 1: start pocketbase
> * node 1: start nats-server
> * wait 10 seconds
> * node 1: start marmot
> * later....
> * node 2: start pocketbase
> * node 2: start nats-server
> * wait 10 seconds
> * node 2: start marmot


Ok so here is my Procfile (I use goreman):

```
pocketbase1: ./pocketbase --dir pb1 serve --http 0.0.0.0:8091
pocketbase2: ./pocketbase --dir pb2 serve --http 0.0.0.0:8092
nats-1: nats-server -c ./nats/nats1.conf
nats-2: nats-server -c ./nats/nats2.conf
```

It just brings up two `pocketbase` servers with two `nats-servers`. After booting them off I did took snapshot from first node like this:

![image](https://user-images.githubusercontent.com/22441/199356647-fae97a03-05af-4cc2-9d22-f3ddaacc1c84.png)

Then simply started the server on node 2 

![image](https://user-images.githubusercontent.com/22441/199356949-30d62c8e-ca5d-47c2-959f-6e1e7f89e0eb.png)

My `marmot1.toml` looks like this:

```toml
# Path to target SQLite database
 db_path="./pb1/data.db"

 # ID to uniquely identify your nodes in your cluster
 # It's recommended to always configure this
 node_id=1

 # Path to persist the saved sequence map on disk for warm reboot
 # If this file is missing Marmot has to download snapshot
 # and replay all logs in order to restore database
 seq_map_path="/tmp/node1-seq-map.cbor"


 # Snapshots are used to limit log size and have a database snapshot backedup on your
 # configured blob storage (NATS for now). This helps speedier recovery or cold boot
 # nodes to come up. A Snapshot is taken every log entries are close to max_entries
 # configured in replication_log section. It's recommended to use a large value
 # for maximum entries in replication log, because SQLite can do 1000s of TPS
 # replaying a couple thousands of entries should be really quick.
 [snapshot]
 # Disabling snapshot disables both restore and save
 enabled=true
 # Number of NATS replicas of snapshot object store (max 5)
 replicas=1


 # Change log that is published and persisted in JetStreams by Marmot.
 # Marmot auto-configures missing JetStreams when booting up for you.
 [replication_log]
 # Number of replicas per log to configure
 replicas=1
 # Number of shards to divide the logs over, each JetStream and subject will be prefixed
 # by the configured `subject_prefix` and `stream_prefix` under nats
 shards=4
 # Max log entries JetStream should persist, JetStream is configured to drop older entries
 # Each JetStream is configured to persist on file.
 max_entries=1024
 # Enable log compression, uses zstd to compress logs as they are streamd to NATS
 # This is useful for DB storing large blobs that can be compressed.
 compress=true


 # NATS server configurations
 [nats]
 # List of NATS server to use as boot server. Reference NATS documentation on how to pass
 # authentication credentials as part of URL.
 urls=[
     "nats://localhost:4222",
     "nats://localhost:4223"
 ]
 # Subject prefix used when publishing log entries, it's usually suffixed by shard number
 # to get the full subject name
 subject_prefix="marmot-change-log"
 # JetStream name prefix used for publishing log entries, it's usually suffixed by shard number
 # to get the full JetStream name
 stream_prefix="marmot-changes"


 # Console STDOUT configurations
 [logging]
 # Configure console logging
 verbose=true
 # "console" | "json"
 format="console"
```

My `marmot2.toml` is copy of `marmot1.toml` with node and DB path changes.

**Comment by maxpert** [comment] 2022-11-01 22:58
> I guess the main issue I'm having is this: marmot crashes if only the current node is running. So I can't easily bootstrap things. I want to start up pocketbase, create an admin, create a collection, then create a snapshot, then start up the 2nd node so they're in sync.
> 
> If I start up both nodes, then pocketbase is already running on the second node and it creates the database, and it doesn't sync. What's the best way to do this programmatically, so I can start with one node, seed it with data, then start up additional nodes?


For sake of my clarity when you are bringing up second `marmot` the PB server is running already? With an existing DB? I just want to make sure that I am capturing the scenario correctly first. Now that you are over the NATS error I suspect something else to be wrong. Make sure both marmots are not pointing to same `seq_map_path` file. Otherwise second marmot will imagine the sequence is already caught up.

**Comment by burggraf** [comment] 2022-11-02 14:33
> Make sure both marmots are not pointing to same seq_map_path file. 
These are completely different machines, so that wouldn't be possible.

I think I understand what's going on now, but there's still an issue that marmot won't start if there aren't any other peers running.  Is it possible to modify it so that it won't just crash, but rather wait?  The scenario is that if the peers are down, marmot crashes, then the peers come back up later, but marmot isn't running.  I could write a service for this that restarts marmot if it isn't running, but that's an extra step I'd like to avoid.

To see this in action try it with a single node:

```
pocketbase1: ./pocketbase --dir pb1 serve --http 0.0.0.0:8091
nats-1: nats-server -c ./nats/nats1.conf
marmot-1: sleep 20 && marmot -config marmot-1.toml
```

**Comment by maxpert** [comment] 2022-11-02 17:41
> > Make sure both marmots are not pointing to same seq_map_path file.
> > These are completely different machines, so that wouldn't be possible.
> 
> I think I understand what's going on now, but there's still an issue that marmot won't start if there aren't any other peers running. Is it possible to modify it so that it won't just crash, but rather wait? The scenario is that if the peers are down, marmot crashes, then the peers come back up later, but marmot isn't running. I could write a service for this that restarts marmot if it isn't running, but that's an extra step I'd like to avoid.
> 
> To see this in action try it with a single node:
> 
> ```
> pocketbase1: ./pocketbase --dir pb1 serve --http 0.0.0.0:8091
> nats-1: nats-server -c ./nats/nats1.conf
> marmot-1: sleep 20 && marmot -config marmot-1.toml
> ```

So marmot can run standalone (just verified) when there is no other issue. I think what you are struggling with is a different problem. Probably due to DB being locked when Marmot boots up. What error is marmot throwing you if the running it standalone?

**Comment by burggraf** [comment] 2022-11-02 17:49
When I run the services listed above, here's the error:

```
10:48:17    marmot-1 | 10:48AM DBG Opening database path=./pb1/data.db
10:48:17    marmot-1 | 10:48AM DBG Forcing WAL checkpoint
10:48:18    marmot-1 | 10:48AM PNC Unable to initialize replicators error="nats: JetStream system temporarily unavailable"
10:48:18    marmot-1 | panic: Unable to initialize replicators
10:48:18    marmot-1 | goroutine 1 [running]:
10:48:18    marmot-1 | github.com/rs/zerolog.(*Logger).Panic.func1({0x4659062?, 0x0?})
10:48:18    marmot-1 | 	/Users/markb/go/pkg/mod/github.com/rs/zerolog@v1.27.0/log.go:359 +0x2d
10:48:18    marmot-1 | github.com/rs/zerolog.(*Event).msg(0xc000110120, {0x4659062, 0x20})
10:48:18    marmot-1 | 	/Users/markb/go/pkg/mod/github.com/rs/zerolog@v1.27.0/event.go:156 +0x2a5
10:48:18    marmot-1 | github.com/rs/zerolog.(*Event).Msg(...)
10:48:18    marmot-1 | 	/Users/markb/go/pkg/mod/github.com/rs/zerolog@v1.27.0/event.go:108
10:48:18    marmot-1 | main.main()
10:48:18    marmot-1 | 	/Users/markb/dev/marmot/marmot/marmot.go:65 +0x77e
10:48:18    marmot-1 | Terminating marmot-1

```

**Comment by maxpert** [comment] 2022-11-02 17:57
I think I know what you are doing. Since you have configured NATS to be a cluster with peer nodes, and none of them are up. The NATS itself is not ready to accept JetStream traffic. Either bring up the other NATS nodes, and then Marmot will just come up, or remove peer nodes from single NATS server (you can make other nodes join a cluster later as well, and those changes will be propagate to clients).

**Comment by burggraf** [comment] 2022-11-03 13:02
I got rid of the cluster with peer nodes part (my mistake there) but I still can't get a basic configuration up that allows me to start one instance, enter some data, then start a second instance and get that second instance to initialize the current version of data and then sync moving on.  

There should be a working example of this somewhere, as that's the major use case for this project (not running 3 nodes on a single machine, but rather running individual nodes on separate machines across the internet to distribute load and create redundancy).  Would it be possible to create a basic demo of how to set that up?

**Comment by maxpert** [comment] 2022-11-03 13:57
Yes I am already in talks with Digital Ocean getting a tier that will allow us to build a full demo of multi-region replication. Also somebody else had a good instructions on getting started as well https://github.com/maxpert/marmot/discussions/33

I will combine these together to put together something that will be online and easy to setup locally as well (maybe a shell script)

**Comment by burggraf** [comment] 2022-11-03 15:39
Ideally there should be an example for setting it up using docker and hosting services such as Digital Ocean along with a Fly.io example for hosting there.  😄

**Comment by maxpert** [comment] 2022-11-03 20:56
Absolutely! I would appreciate any contributions as well. Since I am not a fly.io user it will take me more time to document this stuff. Somebody who is already experienced can do it quicker than me. Marking this as help wanted as well, so that if somebody can do it earlier than me I would be more than happy to accept PR. 

RN I am focused on snapshot storage on S3 compatible storage.

**Comment by burggraf** [comment] 2022-11-03 21:40
RE: snapshot storage on S3, maybe look at what [LItestream](https://litestream.io/) is doing.

**Comment by maxpert** [comment] 2022-11-17 15:14
So for status update S3 support has been merged and now snapshots can be saved/restored on S3 compatible APIs. Up next will be some documentation work (getting started) and maybe a quick start shell script.

**Closed** 2023-07-26 14:14 UTC
Labels: documentation, help wanted, good first issue
